CONSOLE_ENABLE = no
VIA_ENABLE = no
WPM_ENABLE = yes
OLED_DRIVER = SSD1306
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
TAP_DANCE_ENABLE = yes

# Additional thing to reduce compiled size
LTO_ENABLE = yes
NO_USB_STARTUP_CHECK = yes
